
openapi: 3.0.1
info:
  title: 翻译插件
  description: 这个插件提供文本翻译服务，支持多种语言之间的互译，具备简洁易用的用户界面和功能。
  version: "v1"
servers:
  - url: http://127.0.0.1:8080/
paths:
  /translate:
    post:
      operationId: translateText
      summary: 文本翻译
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/translateTextRequest"
      responses:
        "200":
          description: 翻译成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/translateTextResponse"
components:
  schemas:
    translateTextRequest:
      type: object
      required: [text, source_language, target_language]
      properties:
        text:
          type: string
          description: 需要翻译的文本
        source_language:
          type: string
          description: 源语言
        target_language:
          type: string
          description: 目标语言
    translateTextResponse:
      type: object
      required: [translated_text]
      properties:
        translated_text:
          type: string
          description: 翻译后的文本
